"""Audit state schema for the switch vulnerability detection graph.

Every field is a first-class observable: each node reads from and writes
to this schema, which means any step can be checkpointed and replayed.

Design principle: state is the audit log — if something happened but
isn't in the state, it didn't happen.
"""

from typing import Annotated

from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AuditState(TypedDict):
    # ── LangGraph managed ──────────────────────────────────────────────
    # add_messages reducer: new messages are appended, not replaced
    messages: Annotated[list, add_messages]

    # ── Session context ────────────────────────────────────────────────
    session_id: str
    target: str          # device IP / hostname / serial path

    # ── Audit loop ─────────────────────────────────────────────────────
    # Current hypothesis being tested (generated by the think node)
    hypothesis: str
    # Accumulated observations from the device (appended by the observe node)
    observations: list[str]
    # Number of completed think → act → observe cycles
    trial_count: int
    # "running" | "completed" | "error"
    status: str
